apiVersion: v1
kind: Namespace
metadata:
  name: ros-vnc-suffix

---

apiVersion: v1
kind: Service
metadata:
  namespace: ros-vnc-suffix
  labels:
    app: ros-vnc
  name: ros-vnc
spec:
  type: NodePort
  ports:
    - name: http
      port: 6080
      nodePort: svcPort
      protocol: TCP
  selector:
    app: ros-vnc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ros-vnc-suffix
  labels:
    app: ros-vnc
  name: ros-vnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-vnc
  template:
    metadata:
      labels:
        app: ros-vnc
    spec:
      dnsConfig:
        nameservers:
          - 202.18.86.8
          - 202.18.86.9
      containers:
      - name: vncserver
        image: rashoru/vnc-humble:latest
        livenessProbe:
          tcpSocket:
            port: 5900
          initialDelaySeconds: 30
          periodSeconds: 5
        ports:
        - containerPort: 5900
      - name: vncclient
        image: rashoru/novnc:bullseye-slim-20230220
        command: ["websockify", "--web=/usr/share/novnc", "6080", "localhost:5900"]
        livenessProbe:
          httpGet:
            path: /vnc.html
            port: 6080
          initialDelaySeconds: 30
          periodSeconds: 5
        ports:
        - containerPort: 6080

